/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/

fn is_even(num: int) -> bool {
    0 == num % 2
}

fn main()
{
    static MAX_NUMBER: int = 4000000;
    let mut f1 = 1;
    let mut f2 = 2;
    let mut sum = 0;

    while true {
        if is_even(f1) {
            sum += f1;
        }
        if is_even(f2) {
            sum += f2;
        }
        // calculate 2 terms of the fibonacci sequence at a time
        f1 = f1 + f2;
        f2 = f2 + f1;
        if f1 > MAX_NUMBER {
            break;
        }
    }

    println!("{}",sum);
}
